AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hotel Booking Backend - Multi-Lambda Architecture

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64
    VpcConfig:
      SecurityGroupIds:
        - sg-0f8aa0b56c8deacb5
      SubnetIds:
        - subnet-0d51dc6d4afc18ef9
    Environment:
      Variables:
        MONGO_URI: ""
        JWT_SECRET: ""

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas/authHandler.authHandler
      Events:
        AuthBaseRoute:
          Type: HttpApi
          Properties:
            Path: /api/auth
            Method: ANY
        AuthProxyRoute:
          Type: HttpApi
          Properties:
            Path: /api/auth/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "node24"
        EntryPoints:
          - lambdas/authHandler.ts

  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas/userHandler.userHandler 
      Events:
        UserBaseRoute:
          Type: HttpApi
          Properties:
            Path: /api/users
            Method: ANY
        UserProxyRoute:
          Type: HttpApi
          Properties:
            Path: /api/users/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "node24"
        EntryPoints:
          - lambdas/userHandler.ts

  RoomFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambdas/roomHandler.roomHandler 
      Events:
        RoomBaseRoute:
          Type: HttpApi
          Properties:
            Path: /api/rooms
            Method: ANY
        RoomProxyRoute:
          Type: HttpApi
          Properties:
            Path: /api/rooms/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "node24"
        EntryPoints:
          - lambdas/roomHandler.ts